backend:
  name: git-gateway

display_url: https://beta.strateg.se
publish_mode: editorial_workflow
media_folder: 'content/media/uploads'

collections:
  - name: case
    label: Case
    folder: '/content/case'
    slug: '{{client}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'excerpt', label: 'Excerpt', widget: 'text' }
      - { name: 'client', label: 'Client', widget: 'string' }
      - {
          name: 'date',
          label: 'Publish date',
          widget: 'datetime',
          format: 'Y-MM-DDThh:mm:ssZ',
        }
      - {
          name: 'image',
          label: 'Featured image',
          widget: 'image',
          required: false,
        }
      - {
          name: 'tags',
          label: 'Tags',
          widget: 'select',
          multiple: true,
          required: false,
          options:
            [Digitalt, Identitet, Kampanj, Print, Varumärkesarbete, Video],
        }
      - {
          name: 'contact_relation',
          label: 'Contact',
          widget: 'relation',
          collection: 'employees',
          valueField: 'email',
          searchFields: ['first_name', 'last_name'],
          displayFields: ['first_name', 'last_name'],
        }
      - { name: 'body', label: 'Body', widget: 'markdown' }

  - name: 'articles'
    label: 'Articles'
    label_singular: 'Article'
    folder: '/content/aktuellt'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    editor:
      preview: false
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'excerpt', label: 'Excerpt', widget: 'text' }
      - { name: 'date', label: 'Publish date', widget: 'datetime' }
      - {
          name: 'image',
          label: 'Featured image',
          widget: 'image',
          required: false,
        }
      - { name: 'tags', label: 'Tags', widget: 'list', required: false }
      - { name: 'body', label: 'Body', widget: 'markdown' }
      - { name: 'redirect_from', label: 'Redirect', widget: 'list' }

  - name: 'employees'
    label: 'Employees'
    label_singular: 'Employee'
    folder: '/content/employees'
    slug: '{{first_name}}-{{last_name}}'
    identifier_field: 'email'
    create: true
    editor:
      preview: false
    fields:
      - { name: 'first_name', label: 'First name', widget: 'string' }
      - { name: 'last_name', label: 'Last name', widget: 'string' }
      - { name: 'role', label: 'Role', widget: 'string' }
      - { name: 'email', label: 'Email', widget: 'string' }
      - { name: 'phone', label: 'Phone', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    delete: false
    editor:
      preview: false
    files:
      - name: 'index'
        label: 'Start'
        file: 'content/pages/index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - name: 'about'
        label: 'About'
        file: 'content/pages/vad-vi-gor.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - name: 'career'
        label: 'Career'
        file: 'content/pages/bli-en-av-oss.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - name: 'news'
        label: 'News'
        file: 'content/pages/aktuellt.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text' }
      - name: 'contact'
        label: 'Contact'
        file: 'content/pages/kontakt.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Excerpt', name: 'excerpt', widget: 'text' }

  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        label_singular: 'Site setting'
        file: 'content/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Site name', name: 'name', widget: 'string' }
          - label: 'Contact details'
            name: 'contact'
            widget: 'object'
            fields:
              - { label: 'Address', name: 'address', widget: 'string' }
              - { label: 'Zipcode', name: 'zipcode', widget: 'string' }
              - { label: 'City', name: 'city', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Phone', name: 'phone', widget: 'string' }
          - label: 'Social'
            name: 'social'
            widget: 'object'
            fields:
              - { label: 'Facebook', name: 'facebook', widget: 'string' }
              - {
                  label: 'Facebook App ID',
                  name: 'facebook_app_id',
                  widget: 'string',
                }
              - { label: 'Instagram', name: 'instagram', widget: 'string' }
              - { label: 'LinkedIn', name: 'linkedin', widget: 'string' }
              - { label: 'GitHub', name: 'github', widget: 'string' }
